POST http://localhost:9000/api/auth/signup 
Content-Type: application/json

###
POST http://localhost:9000/api/auth/login
Content-Type: application/json


###
POST http://localhost:9000/api/scores/add
Content-Type: application/json
"


###
GET http://localhost:9000/api/scores
Content-Type: application/json

POST  http://localhost:9000/api/draws/run
Content-Type: application/json


###
GET  http://localhost:9000/api/draws
Content-Type: application/json



###
GET http://localhost:9000/api/admin/winners


###
GET http://localhost:9000/api/admin/stats
